### ISSUE TITLE
[FEAT] Design Tokens should allow bidirectional updates

### ISSUE THREAD

**Issue by schilchSICKAG** [SickDesignSystem/sds#10]
**Description**:

As a designer, I want to the repositories tokens to automatically update when I change design tokens in Figma. As a developer, I want the Figma tokens to automatically update when I change one or more tokens in the repository. 

**Rationale**:

A bidirectional sync for our common design language is needed to prevent divergence between Design (Figma) and Development (components).

---

> ⚠️ The first draft for the tokens was already implemented in #9.
> You may use this package (@sick-design-system/design-tokens) as a base for further work.

**Comment by reichst1SICKAG** [comment]
The Tokens plugin needs a default branch for syncing.
Should this be "main", "develop" or "token" ?

**Comment by klaarseSICKAG** [comment]
Idea: create a tokens branch and setup sync

**Comment by klaarseSICKAG** [comment]
storybook breaks with current token set. to be fixed...
