### ISSUE TITLE
[DOC] Evaluate automatic generation of storybook knobs from components.json

### ISSUE THREAD

**Issue by schilchSICKAG** [SickDesignSystem/sds#24]
**Description**:

As a developer, I do not want to manually configure each property for a component in Storybook. Therefore, a utility is needed that makes it possible to create default props for stories.

**Rationale**:

This is needed so save time and can be seen in various frameworks (e.g. when using Stencil or Lit).

**Comment by klaarseSICKAG** [comment]
Only relevant for FAST. Will be solved with https://github.com/SickDesignSystem/sds/tree/feat/integrate-shoelace-cli
